# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 00:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('encrypted', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='documents')),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('encrypted', models.BooleanField(default=False)),
                ('encryptionKey', models.CharField(blank=True, default='', max_length=100)),
                ('filename', models.FileField(blank=True, upload_to='documents')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.CreateModel(
            name='Group1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups1',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('time', models.DateField(blank=True, default=None, null=True)),
                ('to_encrypt', models.BooleanField(default=False)),
                ('key', models.TextField(blank=True, max_length=10000, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('C', 'Company'), ('I', 'Investor'), ('N/A', 'not declared')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='', max_length=60)),
                ('date', models.CharField(default=datetime.date.today, max_length=200)),
                ('title', models.CharField(default='', max_length=100)),
                ('company', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=12)),
                ('location', models.CharField(default='', max_length=60)),
                ('country', models.CharField(default='', max_length=60)),
                ('industry', models.CharField(default='', max_length=60)),
                ('projects', models.TextField(default='')),
                ('private', models.BooleanField()),
                ('files', models.ManyToManyField(blank=True, to='Lokahi_Fintech.File')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lokahi_Fintech.Report'),
        ),
        migrations.AddField(
            model_name='document',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lokahi_Fintech.Report'),
        ),
    ]
