# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    #dependencies = [
     #   "0001_initial.py"
    #]

    operations = [
    ]
